enum SauceType {
    MOLHOSIMPLE = "MOLHOSILMPLES",
    MOLHOTRADICIONAL = "MOLHOTRADICIONAL",
    MOLHOVEGANO = "MOLHOVEGANO",
    MOLHOAPIMENTADO = "MOLHOAPIMENTADO",
    MOLHOVINAGRETE = "MOLHOVINAGRETE",
}
export default SauceType;